config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'home#index'

	resources :products

	resources :cart_items, only: [:destroy]

	get '/cart', to: 'carts#index'

	get '/cart/add', to: 'carts#add'

  	get '/cart/checkout', to: 'carts#checkout'

  	get '/cart/:id', to: 'carts#show', as: 'carts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :cart_items
	belongs_to :user

	def subtotal
		cart_items.inject(0) do |sum, item|
			sum + item.product.price.to_i
		end
	end

  def tax
    subtotal * 0.1
  end

  def total
    subtotal + tax
  end

  def checkout!
    update(checked_out: true)
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart 
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :carts

   def has_money_for?(cart)
     balance >= cart.total
   end

   def pay_and_checkout!(cart)
      pay!(cart.total) && cart.checkout! if has_money_for?(cart)
   end

   def pay!(total)
     update(balance: balance - total)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	def destroy
		cart_item = CartItem.find(params[:id])

		cart_item.destroy

		redirect_to cart_path
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_or_create_cart

  def index
    @cart_items = @cart.cart_items
  end

  def add
    @cart.cart_items.create(product_id: params[:product])

    redirect_to '/cart'
  end

  def checkout
    current_user.pay_and_checkout!(@cart)

    redirect_to carts_path(@cart)
  end

  def show
    @checked_out_cart = current_user.carts.where(id: params[:id], checked_out: true).last

    redirect_to root_path if @checked_out_cart.nil?
  end

  private

  def find_or_create_cart
    @cart = current_user.carts.where(checked_out: false).last

    if @cart.nil?
      @cart = current_user.carts.create
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :authenticate_user!

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update		
		@product = Product.find(params[:id])

		@product.update(product_params)

		redirect_to products_path(@product)
	end

	def create
		product = Product.create(product_params)

		redirect_to products_path(product)
	end

	def destroy
		@product = Product.find(params[:id])

		@product.destroy	
		
		redirect_to products_path	
	end

	private

	def product_params
		params.require(:product).permit(:name, :description, :photo, :price)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb
<div class="row">
	<h1>Cart</h1>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">No.</th>
				<th scope="col">Product Name</th>
				<th scope="col">Price</th>
				<th scope="col">Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @cart_items.each_with_index do |cart_item, index| %>
				<tr>
					<td scope="row"><%= index + 1 %></td>
					<td><%= cart_item.product.name %></td>
					<td><%= cart_item.product.price %></td>
					<td>
						<%= link_to 'Delete', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %>
					</td>
				</tr>
			<% end %>

  			<tr>
  					<td scope="row"></td>
  					<td>Subtotal:</td>
  					<td><%= @cart.subtotal %></td>
  					<td></td>
        </tr>
  			<tr>
  					<td scope="row"></td>
  					<td>Tax (10%): </td>
  					<td><%= @cart.tax.round %></td>
  					<td></td>
        </tr>
  			<tr>
  					<td scope="row"></td>
  					<td><strong>Total: </strong></td>
  					<td><strong>AMD: <%= @cart.total.round %></strong></td>
  					<td></td>
        </tr>
		</tbody>
	</table>
  <div class="col-lg-12">
    <% if @cart.cart_items.empty? %>
      <div class="alert alert-info">You have no items in your cart :(</div>
    <% elsif current_user.has_money_for?(@cart) %>
      <%= link_to 'Checkout', cart_checkout_path(@cart), class: 'btn btn-success' %>
    <% else %>
      <div class="alert alert-danger">You have insufficient money to purchase the products!</div>
    <% end %>
  </div>
</div>

app/views/carts/show.html.erb
<div class="row">
  <div class="col-lg-6">
    <h1>Receipt</h1>
    <h3>You have successfully purchased the following items</h3>
  </div>

  <div class="col-lg-12">
  	<table class="table">
  		<thead>
  			<tr>
  				<th scope="col">No.</th>
  				<th scope="col">Product Name</th>
  				<th scope="col">Price</th>
  			</tr>
  		</thead>
  		<tbody>
  			<% @checked_out_cart.cart_items.each_with_index do |cart_item, index| %>
  				<tr>
  					<td scope="row"><%= index + 1 %></td>
  					<td><%= cart_item.product.name %></td>
  					<td><%= cart_item.product.price %></td>
  				</tr>
  			<% end %>

  			<tr>
  					<td scope="row"></td>
  					<td>Subtotal:</td>
  					<td><%= @checked_out_cart.subtotal %></td>
        </tr>
  			<tr>
  					<td scope="row"></td>
  					<td>Tax (10%):</td>
  					<td><%= @checked_out_cart.tax.round %></td>
        </tr>
  			<tr>
  					<td scope="row"></td>
  					<td><strong>Total: </strong></td>
  					<td><strong><%= @checked_out_cart.total.round %> AED</strong></td>
        </tr>
  		</tbody>
  	</table>
  </div>

app/views/home/index.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="http://www.coca-colarussia.ru/content/dam/journey/ru/ru/private/2018/09/fanta-instamix/0-zahod-940-fanta-instamix-new-2.png" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://www.stealingshare.com/wp-content/uploads/2014/07/Up-Products.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://d2wvksc3i53c0p.cloudfront.net/media/catalog/product/cache/2/image/1800x/6b9ffbf72458f4fd2d3cb995d92e8889/s/a/sac_6-pack-bottle-update-cz-2_2.png" alt="Third slide">
    </div>
  </div>
</div>
<div class="row">
	<% @products.each do |product| %>
		<div class="col-lg-4 col-md-6 mb-4">
			<div class="card h-100">
				<%= image_tag(product.photo, class: "card-img-top", style: "width: 100px; margin: auto; margin-top: 10px;") unless product.photo.nil? %>
				<div class="card-body">
					<h4><%= product.name %></h4>
					<h5><%= product.price %> AED </h5>
					<p class="card-text"><%= product.description %></p>
				</div>
				<div class="card-footer">
					<%= link_to 'Add to cart', cart_add_path(product: product.id), class: 'btn btn-primary' %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">GoShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-link">
                <a class="btn btn-primary" href="<%= new_product_path %>">Hello, <%= current_user.email %></a>
              </li>
              <li class="nav-link">
                <a class="nav-link" href="">Balance: <%= current_user.balance %></a>
              </li>
              <li class="nav-link">
                <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>
              </li>
              <div class="marg">
                <li class="nav-item">
                  <%= link_to cart_path, class: 'btn btn-primary' do %>
                  <img src="http://www.pngmart.com/files/7/Cart-PNG-Clipart.png" style="width: 25px; height: 25px;">
                  <% end %>
                </li>
              </div>
            <% else %>
              <li class="nav-link">
                <%= link_to('Login', new_user_session_path, class: 'nav-link') %>
              </li>
              <li class="nav-link">
                <%= link_to('Sign up', new_user_registration_path, class: 'nav-link') %>
              </li>
            <% end %>
            
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit students</h1>

<%= form_for @product do |form| %>
	<p class="name"><%= form.label :name %></p>
	<%= form.text_field :name %>
	<br>
	<p><%= form.label :description %></p>
	<%= form.text_field :description %>
	<br>
	<p><%= form.label :photo %></p>
	<%= form.text_field :photo %>
	<br>
	<p class="price"><%= form.label :price %></p>
	<%= form.text_field :price %>
	<br>
	<%= form.submit 'Save changes' %>
<% end %>

app/views/products/index.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-lg-4 col-md-6 mb-4">
			<div class="card h-100">
				<%= image_tag(product.photo, class: "card-img-top", style: "width: 100px; margin: auto;") unless product.photo.nil? %>
				<div class="card-body">
					<h4><%= product.name %></h4>
					<h5>AMD: <%= product.price %></h5>	
					<p class="card-text"><%= product.description %></p>
				</div>
				<div class="card-footer">
					<%= link_to 'Add to cart', cart_add_path(product: product.id), class: 'btn btn-primary' %>
					<%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary' %>
					<%= link_to 'Delete', product, method: :delete, date: {confirm: 'Are you sure?'}, class: 'btn btn-primary' %>
				</div>
			</div>
		</div>		
	<% end%>

</div>
<%= link_to 'Add', new_product_path, class: 'add btn btn-primary'  %>

app/views/products/new.html.erb
<h1 class="main">Add new product</h1>
<div class="aauto">
	<%= form_for @product do |form| %>
		<p class="name"><%= form.label :name %></p>
		<%= form.text_field :name %>
		<br>
		<p><%= form.label :description %></p>
		<%= form.text_field :description %>
		<br>
		<p><%= form.label :photo %></p>
		<%= form.text_field :photo %>
		<br>
		<p class="price"><%= form.label :price %></p>
		<%= form.text_field :price %>
		<br>
		<%= form.submit class: 'create' %>
		<% end %>
	</div>

app/views/products/show.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-lg-4 col-md-6 mb-4">
			<div class="card h-100">
				<%= image_tag(product.photo, class: "card-img-top", style: "width: 100px; margin: auto;") unless product.photo.nil? %>
				<div class="card-body">
					<h4><%= product.name %></h4>
					<h5>AMD: <%= product.price %></h5>
					<p class="card-text"><%= product.description %></p>
				</div>
				<div class="card-footer">
					<%= link_to 'Add to cart', '#', class: 'btn btn-primary' %>
				</div>
			</div>
		</div>		
	<% end%>

</div>